#!/usr/bin/env bash
# Build the Neuroglancer fork and install it as ngllib's packaged viewer.
#
# The result lands in src/ngllib/viewer/ and IS COMMITTED: a clone then has a
# working viewer, and a wheel carries it as package data. Run this only when the
# viewer needs to change -- webpack content-hashes every filename, so a rebuild
# is a new set of files, not a diff.
#
# Requires node (the fork's engines field says >=20.10; 24.x works) and npm.
# Nothing in ngllib imports this script; it is a maintainer tool.
#
#   bash scripts/build_viewer.sh [--fork-dir ../neuroglancer] [--allow-dirty]
set -euo pipefail

FORK_DIR=../neuroglancer
ALLOW_DIRTY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --fork-dir) FORK_DIR=$2; shift 2 ;;
    --allow-dirty) ALLOW_DIRTY=1; shift ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

HERE=$(cd "$(dirname "$0")/.." && pwd)
DEST=$HERE/src/ngllib/viewer
FORK=$(cd "$FORK_DIR" && pwd)
[ -f "$FORK/package.json" ] || { echo "no package.json in $FORK -- clone seung-lab/neuroglancer there" >&2; exit 1; }

COMMIT=$(git -C "$FORK" rev-parse HEAD)
BRANCH=$(git -C "$FORK" rev-parse --abbrev-ref HEAD)
REMOTE=$(git -C "$FORK" config --get remote.origin.url)
DIRTY=false
if [ -n "$(git -C "$FORK" status --porcelain)" ]; then
  DIRTY=true
  # A dirty tree means the shipped bytes cannot be reproduced from a commit,
  # which is the whole point of recording provenance.
  [ "$ALLOW_DIRTY" = 1 ] || {
    echo "fork tree at $FORK has uncommitted changes; commit them or pass --allow-dirty" >&2
    git -C "$FORK" status --porcelain >&2
    exit 1
  }
fi

echo "building $REMOTE $BRANCH @ ${COMMIT:0:12} (dirty=$DIRTY)"
( cd "$FORK" && { [ -d node_modules ] || npm ci; } && npm run build )
[ -f "$FORK/dist/client/index.html" ] || { echo "build produced no dist/client/index.html" >&2; exit 1; }

rm -rf "$DEST"
mkdir -p "$DEST"
# Source maps are 60% of the build and useless in a headless renderer.
( cd "$FORK/dist/client" && find . -type f ! -name '*.map' -print0 | tar --null -cf - -T - ) \
  | tar -xf - -C "$DEST"

# Apache-2.0 requires the licence text, retained notices, and a statement of
# changes when redistributing a modified build (section 4).
cp "$FORK/LICENSE" "$DEST/LICENSE"
cat > "$DEST/NOTICE" <<NOTICE
This directory contains a compiled, MODIFIED build of Neuroglancer.

Upstream:      https://github.com/google/neuroglancer (Apache License 2.0)
Modifications: $REMOTE
               branch $BRANCH, commit $COMMIT
               The fork retains support for the legacy graphene mesh layout
               (mesh directories with no info file, e.g. FlyWire's
               fly_v31_meshes_v2_062619) that current upstream builds fail to
               load, and adds proofreading and recording features.
Built by:      ngllib scripts/build_viewer.sh

Licensed under the Apache License, Version 2.0; see LICENSE in this directory.
Bundled third-party components retain their own licences; see
THIRD_PARTY_NOTICES.txt.
NOTICE

# Bundled dependency licences, collected rather than hand-written. npm's own
# JSON is the source of truth (a shell walk of node_modules produced platform
# paths and UNKNOWN licences); the production tree is a SUPERSET of what webpack
# actually inlines, which is the safe direction for a notices file.
node -e '
const { execSync } = require("child_process");
const fs = require("fs"), path = require("path");
const root = process.argv[1];
let tree = {};
try {
  tree = JSON.parse(execSync("npm ls --omit=dev --all --json", { cwd: root, maxBuffer: 1 << 26 }).toString());
} catch (e) {
  try { tree = JSON.parse((e.stdout || "").toString() || "{}"); } catch (_) {}
}
const seen = new Map();
(function walk(deps) {
  for (const [name, info] of Object.entries(deps || {})) {
    if (!seen.has(name)) {
      let lic = "UNKNOWN";
      try {
        const pkg = JSON.parse(fs.readFileSync(path.join(root, "node_modules", name, "package.json")));
        lic = pkg.license || (pkg.licenses && pkg.licenses[0] && pkg.licenses[0].type) || lic;
      } catch (_) {}
      seen.set(name, { version: info.version || "", license: lic });
    }
    walk(info.dependencies);
  }
})(tree.dependencies);
const rows = [...seen.entries()].sort((a, b) => a[0].localeCompare(b[0]));
console.log("Third-party components in the production dependency tree of this");
console.log("Neuroglancer build (a superset of what webpack inlines).");
console.log("Generated by ngllib scripts/build_viewer.sh.");
console.log("");
for (const [name, { version, license }] of rows) {
  console.log(name.padEnd(46) + String(version).padEnd(14) + license);
}
' "$FORK" > "$DEST/THIRD_PARTY_NOTICES.txt"

NODE_V=$(node --version)
cat > "$DEST/build.json" <<JSON
{
  "remote": "$REMOTE",
  "branch": "$BRANCH",
  "commit": "$COMMIT",
  "dirty": $DIRTY,
  "node": "$NODE_V",
  "built_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "built_by": "scripts/build_viewer.sh"
}
JSON

echo "installed $(find "$DEST" -type f | wc -l) files, $(du -sh "$DEST" | cut -f1) into src/ngllib/viewer"
echo "commit the result: git add src/ngllib/viewer && git commit"
